name: Android Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools-version: 33.0.2
          ndk-version: 27.2.12479018

      - name: Print environment info
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          echo "RUNNER_TEMP=$RUNNER_TEMP"
          export ANDROID_SDK_ROOT="$RUNNER_TEMP/android-sdk"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          java -version
          sdkmanager --list

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle','**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          export ANDROID_SDK_ROOT="$RUNNER_TEMP/android-sdk"
          ./gradlew assembleDebug --stacktrace
