name: Android Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      ANDROID_SDK_ROOT: ${{ env.RUNNER_TEMP }}/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 Java 11
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      # 安装 Android SDK 和 NDK
      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33               # 你项目目标SDK版本，根据实际修改
          build-tools-version: 33.0.2 # 你项目使用的 build tools 版本
          ndk-version: 27.2.12479018  # 报错中你用的 NDK 版本，保持一致

      # 打印环境变量确认
      - name: Print environment info
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          sdkmanager --list

      # 给 gradlew 加执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 缓存 Gradle 依赖（actions/setup-java 自带缓存，这里可选）
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle','**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 运行 Gradle 构建
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

